import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {normalizeImport,mergeBookmarks,safeUrl} from '../lib/bookmarks.mjs';
import {readStore,updateStore} from '../lib/store.mjs';
const row={id:'1900000000000000001',text:'A synthetic bookmark',author:{name:'Example',username:'example'}};
test('X response uses string IDs and honest partial coverage',()=>{
 const r=normalizeImport({data:[{...row,author:undefined,author_id:'1'}],meta:{next_token:'private-token'}});
 assert.equal(r.bookmarks[0].id,row.id);assert.equal(r.bookmarks[0].author.name,'Unknown author');assert.equal(r.bookmarks[0].url,`https://x.com/i/status/${row.id}`);assert.equal(r.source.coverage,'partial');assert.equal(r.warnings.length,2);assert.ok(!JSON.stringify(r).includes('private-token'));
});
test('joins expanded users and media',()=>{const r=normalizeImport({data:[{id:'42',text:'Example',author_id:'7',attachments:{media_keys:['m']}}],includes:{users:[{id:'7',name:'Example',username:'example'}],media:[{media_key:'m',type:'photo',url:'https://example.com/image.jpg'}]}});assert.equal(r.bookmarks[0].author.username,'example');assert.equal(r.bookmarks[0].media[0].type,'image');});
test('unwraps MCP text and rejects tool errors',()=>{assert.equal(normalizeImport({content:[{type:'text',text:JSON.stringify({data:[row]})}]}).bookmarks.length,1);assert.throws(()=>normalizeImport({isError:true,content:[]}));});
test('rejects unsafe IDs and finite bounds',()=>{assert.equal(normalizeImport([{id:1900000000000000001}]).bookmarks.length,0);assert.throws(()=>normalizeImport(Array(10001).fill(row)));assert.throws(()=>normalizeImport({foo:[]}));});
test('keeps HTML inert plain text and drops executable URLs',()=>{const r=normalizeImport([{...row,text:'<script>alert(1)</script>',url:'javascript:alert(1)',media:[{url:'data:text/html,x'}]}]).bookmarks[0];assert.equal(r.text,'<script>alert(1)</script>');assert.equal(r.media.length,0);assert.ok(r.url.startsWith('https://x.com/'));assert.equal(safeUrl('https://user:pass@example.com'),'');assert.equal(safeUrl('http://example.com'),'');});
test('dedupe updates source while preserving user edits',()=>{const old={...normalizeImport([row]).bookmarks[0],tags:['mine'],summary:'My summary',note:'Keep',favorite:true};const incoming=normalizeImport([{...row,text:'New text',tags:['new']}]).bookmarks;const merged=mergeBookmarks([old],incoming);assert.equal(merged.length,1);assert.equal(merged[0].text,'New text');assert.deepEqual(merged[0].tags,['mine']);assert.equal(merged[0].note,'Keep');assert.equal(merged[0].favorite,true);});
test('provenance never claims AI without declared agent metadata',()=>{assert.equal(normalizeImport([{...row,summary:'Imported'}]).bookmarks[0].enrichment.kind,'imported');assert.equal(normalizeImport([{...row,summary:'Agent summary',enrichment:{kind:'agent',agent:'Example agent',generatedAt:'2026-01-01T00:00:00Z'}}]).bookmarks[0].enrichment.kind,'agent');});
test('duplicate IDs collapse and no missing item is deleted',()=>{assert.equal(normalizeImport([row,row]).bookmarks.length,1);assert.equal(mergeBookmarks([{id:'1'}],[]).length,1);});
test('atomic store serializes concurrent updates',async()=>{const dir=await mkdtemp(join(tmpdir(),'gallery-test-'));try{const path=join(dir,'store.json');await Promise.all(Array.from({length:12},(_,i)=>updateStore(path,s=>({...s,bookmarks:[...s.bookmarks,{id:String(i)}]}))));assert.equal((await readStore(path)).bookmarks.length,12);}finally{await rm(dir,{recursive:true,force:true});}});
test('CLI import export stats round trip on synthetic data',async()=>{const dir=await mkdtemp(join(tmpdir(),'gallery-cli-'));try{const input=join(dir,'input.json'),store=join(dir,'store.json'),output=join(dir,'export.json');await writeFile(input,JSON.stringify([row]));for(const args of [['import',input,'--store',store],['stats','--store',store],['export','--store',store,'--output',output]]){const r=spawnSync(process.execPath,['cli.mjs',...args],{cwd:new URL('..',import.meta.url),encoding:'utf8'});assert.equal(r.status,0,r.stderr);}assert.equal(JSON.parse(await readFile(output,'utf8')).bookmarks[0].id,row.id);}finally{await rm(dir,{recursive:true,force:true});}});

test('raw import accepts subsequent agent enrichment; local clearing remains protected',()=>{const raw=normalizeImport([row]).bookmarks;const enriched=normalizeImport([{...row,summary:'A real agent summary',tags:['Testing'],enrichment:{kind:'agent',agent:'Test agent',generatedAt:'2026-01-01'}}]).bookmarks;assert.equal(mergeBookmarks(raw,enriched)[0].summary,'A real agent summary');const edited={...raw[0],enrichment:{kind:'user'}};assert.equal(mergeBookmarks([edited],enriched)[0].summary,'');});

test('empty X results are valid without data array',()=>{assert.deepEqual(normalizeImport({meta:{result_count:0}}).bookmarks,[]);});
test('user-cleared annotations survive export restore and later enrichment',()=>{const local={...normalizeImport([row]).bookmarks[0],tags:[],summary:'',enrichment:{kind:'user'}};const restored=normalizeImport(JSON.stringify({bookmarks:[local]})).bookmarks;const enriched=normalizeImport([{...row,summary:'Replace',tags:['New'],enrichment:{kind:'agent',agent:'Test',generatedAt:'2026-01-01'}}]).bookmarks;const merged=mergeBookmarks(restored,enriched);assert.equal(merged[0].enrichment.kind,'user');assert.equal(merged[0].summary,'');assert.deepEqual(merged[0].tags,[]);});
test('raw hydrated raw preserves author media and agent enrichment',()=>{const raw=normalizeImport({data:[{id:row.id,text:'Original',author_id:'7'}]}).bookmarks;const hydrated=normalizeImport({data:[{id:row.id,text:'Hydrated',author_id:'7',attachments:{media_keys:['m']},tags:['Testing'],summary:'Summary',enrichment:{kind:'agent',agent:'Test',generatedAt:'2026-01-01'}}],includes:{users:[{id:'7',name:'Example',username:'example'}],media:[{media_key:'m',type:'photo',url:'https://example.com/photo.jpg'}]}}).bookmarks;const first=mergeBookmarks(raw,hydrated);const updated=mergeBookmarks(first,normalizeImport({data:[{id:row.id,text:'Latest',author_id:'7'}]}).bookmarks)[0];assert.equal(updated.text,'Latest');assert.equal(updated.author.username,'example');assert.equal(updated.media.length,1);assert.equal(updated.summary,'Summary');assert.equal(updated.url,`https://x.com/example/status/${row.id}`);assert.equal(updated.sourceFields.author,true);assert.equal(updated.sourceFields.media,true);const cleared=mergeBookmarks([updated],normalizeImport([{...row,media:[]}]).bookmarks)[0];assert.deepEqual(cleared.media,[]);});
test('video thumbnail is an image, actual video URL remains video',()=>{const b=normalizeImport([{...row,media:[{type:'video',preview_image_url:'https://example.com/preview.jpg'},{type:'video',url:'https://example.com/video.mp4'}]}]).bookmarks[0];assert.equal(b.media[0].type,'image');assert.equal(b.media[1].type,'video');});
