// Optional developer-only dependency. This simulates DOM interactions, not browser rendering.
import {fileURLToPath, pathToFileURL} from 'node:url';
import path from 'node:path';
let JSDOM;
try { ({JSDOM} = await import(process.env.UI_TEST_JSDOM ? pathToFileURL(path.resolve(process.env.UI_TEST_JSDOM)).href : 'jsdom')); }
catch { console.error('Optional UI checks require jsdom. Install it in a temporary directory and set UI_TEST_JSDOM to its lib/api.js path. See docs/TESTING.md.'); process.exit(2); }
import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import * as api from '../lib/bookmarks.mjs';
import {demoBookmarks} from '../public/demo.js';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const html=await readFile(root+'/public/index.html','utf8');
const source=(await readFile(root+'/public/app.js','utf8')).replace(/^import .*;\n/gm,'').replace(/init\(\);\s*$/,'window.ready = init();')+'\nwindow.testState=()=>({items,library,demo,server,blocked});';
const tests=[];
const check=(name,fn)=>{fn();tests.push(name);};
async function fixture({saved,serverData,status=404,failStorage=false}={}){
 const dom=new JSDOM(html,{url:'https://commonplace.test',runScripts:'outside-only'}),w=dom.window;
 let memory=saved,download;
 Object.assign(w,api,{demoBookmarks,structuredClone,AbortSignal,Blob,TextEncoder,CSS:{escape:s=>s}});
 Object.defineProperty(w,'localStorage',{value:{getItem:()=>memory??null,setItem:(_,v)=>{if(failStorage)throw Error('quota');memory=v}}});
 w.fetch=async()=>new Response(JSON.stringify(serverData||{error:'Synthetic backend failure'}),{status,headers:{'content-type':'application/json'}});
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
 w.HTMLDialogElement.prototype.close=function(){this.open=false};
 w.URL.createObjectURL=b=>{download=b;return 'blob:https://commonplace.test/export'};
 w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};
 w.eval(source);await w.ready;
 const $=s=>w.document.querySelector(s);
 return {w,$,dom,memory:()=>memory,download:async()=>JSON.parse(await download.text())};
}
const f=await fixture();const {w,$}=f;
check('Fresh static preview starts with 12 fictional samples',()=>{assert.equal(w.testState().demo,true);assert.equal($('.gallery').children.length,12);assert.equal(f.memory(),undefined)});
$('#open-import').click();$('#import-json').value='{bad';await $('#import-submit').onclick();
check('Invalid JSON retains collection and import dialog',()=>{assert.match($('#import-error').textContent,/valid JSON/);assert.equal(w.testState().items.length,12);assert.equal($('#import-dialog').open,true)});
$('#cancel-import').click();$('#open-import').click();
check('Cancel and reopen keep draft without modifying library',()=>{assert.equal($('#import-json').value,'{bad');assert.equal(w.testState().items.length,12)});
$('#import-guide').click();
check('Agent guide closes import and exposes return control',()=>{assert.equal($('#guide-dialog').open,true);assert.equal($('#import-dialog').open,false);assert.equal($('#guide-back').hidden,false)});
$('#guide-back').click();
check('Back to import preserves draft',()=>{assert.equal($('#import-dialog').open,true);assert.equal($('#import-json').value,'{bad')});
$('#import-json').value=JSON.stringify({bookmarks:[{id:'qa-one',text:'A synthetic design idea',author:{name:'QA Author',username:'qatest'},tags:['Design'],summary:'Synthetic summary',enrichment:{kind:'agent',agent:'QA agent',generatedAt:'2026-10-02T00:00:00Z'},media:[{type:'image',url:'https://images.example.test/qa.png'}]},{id:'qa-two',text:'A synthetic coding idea',author:{name:'Second Author'},tags:[]}]});
await $('#import-submit').onclick();
check('First import separates personal library from samples',()=>{assert.equal(w.testState().demo,false);assert.equal(w.testState().items.length,2);assert.equal(w.testState().items.some(b=>b.id.startsWith('demo-')),false);assert.equal(JSON.parse(f.memory()).bookmarks.length,2);assert.equal($('#import-dialog').open,false)});
check('External images have no img/src until explicit opt-in',()=>{assert.equal(w.document.querySelectorAll('img').length,0);assert.equal($('#external-images').checked,false);assert.match($('.media-placeholder').textContent,/kept private/)});
$('#external-images').checked=true;$('#external-images').onchange({target:$('#external-images')});
check('Image opt-in inserts safe source',()=>assert.equal(w.document.querySelector('img').getAttribute('src'),'https://images.example.test/qa.png'));
$('#external-images').checked=false;$('#external-images').onchange({target:$('#external-images')});
check('Opt-out removes external image elements',()=>assert.equal(w.document.querySelectorAll('img').length,0));
$('#search').value='design QA';$('#search').oninput({target:$('#search')});
check('Multiword author and post search matches one bookmark',()=>assert.equal($('.gallery').children.length,1));
$('#search').value='nothing-synthetic';$('#search').oninput({target:$('#search')});
check('No-result search shows recovery action',()=>assert.ok($('#empty-action')));
$('#empty-action').click();
$('[data-favorite="qa-one"]').click();await new Promise(r=>setTimeout(r,20));
$('#mobile-view').value='favorites';$('#mobile-view').onchange({target:$('#mobile-view')});
check('Favorite save and mobile Favorites filter work',()=>{assert.equal(w.testState().items[0].favorite,true);assert.equal($('.gallery').children.length,1);assert.equal($('#favorite-count').textContent,'1')});
$('[data-open="qa-one"]').click();$('#edit-note').value='Should not save';$('#cancel-detail').click();$('[data-open="qa-one"]').click();
check('Cancel detail discards unsaved fields',()=>assert.equal($('#edit-note').value,''));
$('#edit-note').value='Synthetic saved note';await $('#save-detail').onclick();
check('Note-only edit preserves agent enrichment',()=>{assert.equal(w.testState().items[0].note,'Synthetic saved note');assert.equal(w.testState().items[0].enrichment.kind,'agent')});
$('[data-open="qa-one"]').click();$('#edit-tags').value='Edited, Useful';$('#edit-summary').value='A revised synthetic summary';await $('#save-detail').onclick();
check('Tag/summary edit persists and records user enrichment',()=>{assert.equal(w.testState().items[0].summary,'A revised synthetic summary');assert.equal(w.testState().items[0].tags.join(','),'Edited,Useful');assert.equal(w.testState().items[0].enrichment.kind,'user');assert.equal($('#detail-dialog').open,false)});
$('[data-open="qa-one"]').click();$('#edit-tags').value='x'.repeat(61);await $('#save-detail').onclick();
check('Invalid long tags do not close or overwrite saved tags',()=>{assert.match($('#detail-error').textContent,/60 characters/);assert.equal($('#detail-dialog').open,true);assert.equal(w.testState().items[0].tags.join(','),'Edited,Useful')});
$('#cancel-detail').click();$('#export').click();const exported=await f.download();
check('Export contains complete personal library and saved edits',()=>{assert.equal(exported.source.demo,false);assert.equal(exported.bookmarks.length,2);assert.equal(exported.bookmarks[0].note,'Synthetic saved note')});
const refreshed=await fixture({saved:f.memory()});
check('Refresh restores browser collection, edits, favorites and resets media consent',()=>{assert.equal(refreshed.w.testState().demo,false);assert.equal(refreshed.w.testState().items.length,2);assert.equal(refreshed.w.testState().items[0].favorite,true);assert.equal(refreshed.$('#external-images').checked,false)});
$('#open-import').click();$('#import-json').value=JSON.stringify({bookmarks:[{id:'qa-one',text:'Updated source post',tags:['Overwrite'],summary:'Overwrite'}]});await $('#import-submit').onclick();
check('Duplicate re-import refreshes source but keeps local edits',()=>{assert.equal(w.testState().items.length,2);assert.equal(w.testState().items[0].text,'Updated source post');assert.equal(w.testState().items[0].summary,'A revised synthetic summary');assert.equal(w.testState().items[0].favorite,true)});
$('#open-import').click();$('#import-json').value=JSON.stringify({source:{demo:true},bookmarks:demoBookmarks});await $('#import-submit').onclick();
check('Synthetic demo export cannot be mixed into personal library',()=>{assert.match($('#import-error').textContent,/sample export/);assert.equal(w.testState().items.length,2)});
const quota=await fixture({saved:f.memory(),failStorage:true});quota.$('[data-favorite="qa-one"]').click();await new Promise(r=>setTimeout(r,20));
check('Browser storage failure does not mutate displayed or saved bookmark',()=>{assert.equal(quota.w.testState().items[0].favorite,true);assert.match(quota.$('#toast').textContent,/No changes were saved/)});
const failed=await fixture({status:500});
check('Backend failure fails closed without demo fallback',()=>{assert.equal(failed.w.testState().blocked,true);assert.equal(failed.w.testState().demo,false);assert.equal(failed.$('#open-import').disabled,true);assert.match(failed.$('#connection-message').textContent,/Synthetic backend failure/)});
const corrupt=await fixture({saved:'broken'});
check('Corrupt browser storage is never silently reset',()=>{assert.equal(corrupt.w.testState().blocked,true);assert.equal(corrupt.memory(),'broken')});
const node=await fixture({status:200,serverData:{version:1,bookmarks:[]}});
check('Fresh Node library is empty, with separate opt-in sample collection',()=>{assert.equal(node.w.testState().server,true);assert.equal(node.w.testState().demo,false);assert.ok(node.$('#explore-demo'))});
node.$('#explore-demo').click();node.$('[data-favorite]').click();await new Promise(r=>setTimeout(r,20));node.$('#return-library').click();
check('Demo edits do not enter real Node library',()=>assert.equal(node.w.testState().items.length,0));
for(const x of [f,refreshed,quota,failed,corrupt,node])x.dom.window.close();
const report={kind:'DOM simulation (not real-browser or visual QA)',passed:tests.length,tests};
if (process.argv[2]) await writeFile(path.resolve(process.argv[2]),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
